
services:
  web-server:
    image: nginx:latest
    depends_on:
      - database
    container_name: nginx
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '80:80'
    restart: unless-stopped

  database:
    image: postgres:latest
    restart: unless-stopped
    container_name: home_automation_database
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1111
    volumes:
      - ./src/database:/opt/home_automation/sql
      - ./docker/database:/docker-entrypoint-initdb.d
      - postgres_home_automation_data:/var/lib/postgresql

volumes:
  postgres_home_automation_data: