
services:
  web-server:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '80:80'
    restart: unless-stopped
