
services:
  web:
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
        USERNAME: ${USER}
    container_name: home_automation_web
    volumes:
      - .:/home/${USER}/workspace
    working_dir: /home/${USER}/workspace
    user: "${UID}:${GID}"
    depends_on:
      - database
      - web-server
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - private
      - public

  web-server:
    image: nginx:latest
    depends_on:
      - database
    container_name: nginx
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    ports:
      - '443:443'
      - '80:80'
    restart: unless-stopped
    networks:
      - public
      - private

  database:
    image: postgres:latest
    restart: unless-stopped
    container_name: home_automation_database
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1111
    volumes:
      - ./src/database:/opt/home_automation/sql
      - ./docker/database:/docker-entrypoint-initdb.d
      - postgres_home_automation_data:/var/lib/postgresql
    networks:
      - private

volumes:
  postgres_home_automation_data:

networks:
  public:
    driver: bridge
  private:
    driver: bridge